version: '3.8'

services:
  app:
    container_name: api
    image: uiuq/diario-online-backend:0.1

    ports:
      - "8080:8080"
    
    depends_on:
      - postgres-db
    
    networks:
      - default
    
    environment:
      DATABASE_URL: postgres://postgres:Kaju@postgres-db:5432/users
    
    restart: always

  postgres-db:
    container_name: postgresa
    image: postgres

    restart: always

    environment:
      - POSTGRES_DB=notedb
      - POSTGRES_PASSWORD=Kaju
      - POSTGRES_USER=postgres

    ports:
      - '5432:5432'

    networks:
      - default
    
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgres-data:/var/lib/postgresql/data
